library(plm)
data = as.data.frame(dataset)
pdata = pdata.frame(dataset1, index = c("income", "year"))
pooled = plm(lowest_20 ~ gdppc+ Imports+Exports+inflation2, data = pdata, model = "pooling")
summary(pooled)
fixed = plm(lowest_20 ~ gdppc+ Imports+Exports+inflation2, data = pdata, model = "within")
summary(fixed)
random = plm(lowest_20 ~ gdppc+ Imports+Exports+inflation2, data = pdata, model = "random")
summary(random)
phtest(fixed, random)
pFtest(fixed, pooled)
pooltest(lowest_20 ~ GDPpcPPP+Exports+inflation1, data = pdata, model = "within")
lsdv= lm(lowest_20 ~ gdppc+ Imports+Exports+inflation2 + factor(income), data = pdata)
summary(lsdv)
pgrangertest(lowest_20~gdppc, data= pdata)
lsdv1= lm(lowest20 ~  ppp + factor(year)-1, data = pdata)
summary(lsdv1)
fixed_2 = plm(lowest_20 ~ GDPpcPPP+Exports+inflation1, data = pdata, model = "within", effect = "twoways")
summary(fixed_2)